STATEWIDE_PRIMARY_CANDIDATES = {
    # DEM PRESIDENT
    'BERNIE SANDERS',
    'JOSEPH R. BIDEN',
    'TULSI GABBARD',
    # DEM ATTORNEY GENERAL
    'JOSH SHAPIRO',
    # DEM AUDITOR GENERAL
    'H. SCOTT CONKLIN',
    'MICHAEL LAMB',
    'TRACIE FOUNTAIN',
    'ROSE ROSIE MARIE DAVIS',
    'NINA AHMAD',
    'CHRISTINA M. HARTMAN',
    # DEM STATE TREASURER
    'JOE TORSELLA',
    # REP PRESIDENT
    'DONALD J. TRUMP',
    'ROQUE ROCKY DE LA FUENTE',
    'BILL WELD',
    # REP ATTORNEY GENERAL
    'HEATHER HEIDELBAUGH',
    # REP AUDITOR GENERAL
    'TIMOTHY DEFOOR',
    # REP STATE TREASURER
    'STACY L. GARRITY',
}